### PR TITLE
Moc login instance

### PR DESCRIPTION
**Pull request by rob-baron**
Created a new pull request as I had mistakenly had the base set to cyverse/rtwo.  This is a substantial departure from the way that they are using this, so it should only go to the CCI-MOC and not upstream.

### CODE REVIEW

**Comment by xuhang57** [comment]
You don't have to modify rtwo to connect openstack service client api(s).  See init_security_group and floating_up as examples.

**Comment by rob-baron** [comment]
You are absolutely correct, rtwo has always been able to connect to the open stack service client.  This has never been under debate.

Looking at the example of init_security_group (from "service/accounts/openstack_manager.py"). In this function nova is used to increase the security group quota.  This can only be done by an admin, so it would appear that despite rtwo being able to connect to nova without modification, it is not using the user's token, but using the admin's.  With the version that I was working with previously, it was the admin's password, so the code may have changed, it might be the admin's token.

The difficulty I found in getting the user token to be used to build the open stack clients (and excise the god account) is to be able to provide a mechanism to get the token from where we have access to it (a function that has access to the user's identity) to the open stack clients.  Libcloud does this through the use of the kwargs as do several other functions within atmosphere and rtwo.  Many of the modifications that I did in rtwo in order to support token authentication/login use this tactic.  

Also, when things are called from celery (rtwo is often called from celery), has the additional difficulty of parameters not being passed through.  As an example, consider the following snippet from the celery log file:

    File "service/driver.py", line 108, in get_account_driver
        return OSAccountDriver(provider)
    File "service/accounts/openstack_manager.py", line 115, in __init__
        all_creds = self._init_by_provider(provider, *args, **kwargs)

Here the OSAccountDriver only has access to the provider credentials and not the user credentials.  because it is in a separate process it has to open up a new.  The aforementioned tactic works well in this situation, as the OSAccountDriver could then be called with (provider, *args, **kwargs) and the kwargs just need to be passed along to where they will be used to initialize the Openstack clients.

As a side effect these change also effectively remove the "god" account.

There are more elegant approaches to this, I just selected one that I could guarantee would work and didn't require an outright rewrite of two.

**Comment by xuhang57** [comment]
https://github.com/CCI-MOC/GUI-Backend/blob/master/service/instance.py#L1324-L1331
This is what we use currently in the code base. 

locally, I have re-worked it so it is using user's token to authorize neutron client and call security group api(s).

Will send a PR once I finish polishing it.

**Comment by rob-baron** [comment]
OK, that makes sense that the code base has shifted from what I was working on.  Make sure that it works from celery.  Keep in mind that celery does not have necessarily have access to the same state as in the main process.

**Comment by rob-baron** [comment]
I am in the process of rethinking this.  So consider this a work in progress.

**Comment by xuhang57** [comment]
So your change in backend was dependent on rtwo. Have you changed that so this PR could be closed?

**Comment by rob-baron** [comment]
No, my change in the backend was informed based on my understand of how rtwo works.

My changes in rtwo will eventually become important when we remove the demigod account.

**Comment by xuhang57** [comment]
I don't think so. How is that?

**Comment by rob-baron** [comment]
because there are a number of calls that will only use the provider credentials to open a connection to open stack or to libcloud.  Unfortunately, when there is only the provider passed to celery, the specific user is not known.  This can be handled by adding all of the user/provider credentials to the kwargs in a similar manner that libcloud does (which is what the vast majority of my changes do in rtwo).

 You can see an example of this in the previous snippet that I provided above.  For example, once we call OSAccountDriver(provider) we loose access to all of the identity information.  The trivial way to change this is to call OSAccountDriver(provider, identity.get_all_creds())

**Comment by xuhang57** [comment]
Those functions are not called anywhere. So, in the current code base. You will need the admin user to help you get images from the provider. Once get that done. Safely delete that user and it works fine.

**Pull request closed without merging**
